export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_USER_DATA_CORRECTO = "SAVE_USER_DATA_CORRECTO";
export const SAVE_USER_DATA_ERROR = "SAVE_USER_DATA_ERROR";

export const SAVE_DOCUMENT = "SAVE_DOCUMENT";
export const SAVE_DOCUMENT_ERROR = "SAVE_DOCUMENT_ERROR";
