export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_USER_DATA_SUCCESS = "SAVE_USER_DATA_SUCCESS";
export const SAVE_USER_DATA_ERROR = "SAVE_USER_DATA_ERROR";

export const SAVE_DOCUMENT = "SAVE_DOCUMENT";
export const SAVE_DOCUMENT_ERROR = "SAVE_DOCUMENT_ERROR";

export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_ERROR = "GET_DOCUMENTS_ERROR";

export const SET_FILTER_DOCUMENTS = "SET_FILTER_DOCUMENTS";

export const ADD_SIGNER = "ADD_SIGNER";
export const UPDATE_SIGNER = "UPDATE_SIGNER";
export const DELETE_SIGNER = "DELETE_SIGNER";

// Requests

export const POST_DOCUMENT = "POST_DOCUMENT";
export const POST_DOCUMENT_SUCCESS = "POST_DOCUMENT_SUCCESS";
export const POST_DOCUMENT_ERROR = "POST_DOCUMENT_ERROR";

export const DELETE_DOCUMENT = "DELETE_DOCUMENT";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_ERROR = "DELETE_DOCUMENT_ERROR";
